### ISSUE TITLE
troublesome line in chessPiece

### ISSUE THREAD

**Issue by ef23** [ef23/chesspeak#1]
this line either breaks Pawn or causes infinite recursion: 
```
public static int getRow(int rowCol)
	{
		return rowCol%10;
	}
```

probably more ideal to fix Pawn such that there's no off by one: 
```
public static int getRow(int rowCol)
	{
		return (rowCol%10==0)?(rowCol%10+1):(rowCol%10);
	}
```

**Comment by dpeng817** [comment]
Initialization of chessboard and implementation of getRow were not matching, offbyone not causing issue
